### ISSUE TITLE
Compatibility with React Native

### ISSUE THREAD

**Issue by thgh** [joebobmiles/y-react#2] opened 2022-07-10 12:31 UTC
React Native doesn't like .cjs, so it gives this error:
```
Android Bundling failed 334ms
While trying to resolve module `@joebobmiles/y-react` from file `/Users/.../App.tsx`, the package `/Users/.../node_modules/@joebobmiles/y-react/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/.../node_modules/@joebobmiles/y-react/dist/y-react.cjs`. Indeed, none of these files exist:

  * /Users/.../node_modules/@joebobmiles/y-react/dist/y-react.cjs(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
```

An extra build output in rollup.config.js could resolve this.

**Comment by joebobmiles** [comment] 2022-07-11 04:47
If you read `rollup.config.js`, you will see that cjs and mjs versions are already built and should be shipped in the package.

From what I can tell from the output you posted, React Native has choked on the `main` parameter in the `package.json`. this may be because:
1. The package does not make use of the `type` parameter, or
2. React Native does not respect the `exports` parameter during build time.

Are you using a transpiler such as Babel or TypeScript? Can you post a repo that reproduces this issue?

**Comment by joebobmiles** [comment] 2022-07-11 18:19
Reviewing this while I'm not trying to fall asleep and doing a little research, it seems that React Native is expecting `main` to point to a non-compiled file (i.e. not `cjs` or `mjs`). It appears this is [a known issue](https://github.com/facebook/metro/issues/535) that Metro contributors are too busy/lazy to fix, since its two years old at this point and they closed [56 issues](https://github.com/facebook/metro/issues?q=is%3Aissue+closed%3A%3E2020-05-20) and [141 PRs](https://github.com/facebook/metro/pulls?q=is%3Apr+closed%3A%3E2020-05-20) in that time.

That being said, there are two [work](https://github.com/facebook/metro/issues/535#issuecomment-970443661) [arounds](https://github.com/facebook/metro/issues/535#issuecomment-1180120485), one being posted last night. I am going to close this issue and ask that you bother the Metro folks.

**Closed as completed by joebobmiles** 2022-07-11 18:19 UTC
